added player, offer, analytics, order API's, changed project setup
Appcharge/mock-publisher-dotnet6 pull request #5
Opened 2023-10-09 18:42 UTC by AlexPolyakovsky

2023-10-10 12:54 UTC, shaiboujuappcharge requested changes

2023-10-10 12:54 UTC, shaiboujuappcharge commented on WebhookTemplateCS/src/controllers/health/HealthController.cs
> +    [Route("/mocker//health")]
extra `/`?

2023-10-10 12:58 UTC, AlexPolyakovsky commented on WebhookTemplateCS/src/controllers/health/HealthController.cs
> +    [Route("/mocker//health")]
fixed

2023-10-11 10:11 UTC, shaiboujuappcharge approved these changes

2023-10-11 11:41 UTC, merged